export const ACCOUNT_DETAILS_REQUEST = 'ACCOUNT_DETAILS_REQUEST'
export const ACCOUNT_DETAILS_SUCCESS = 'ACCOUNT_DETAILS_SUCCESS'
export const ACCOUNT_DETAILS_FAILURE = 'ACCOUNT_DETAILS_FAILURE'


export const CHAT_DETAILS_REQUEST = 'CHAT_DETAILS_REQUEST'
export const CHAT_DETAILS_SUCCESS = 'CHAT_DETAILS_SUCCESS'
export const CHAT_DETAILS_FAILURE = 'CHAT_DETAILS_FAILURE'



export const TRANSACTION_DETAILS_REQUEST = 'TRANSACTION_DETAILS_REQUEST'
export const TRANSACTION_DETAILS_SUCCESS = 'TRANSACTION_DETAILS_SUCCESS'
export const TRANSACTION_DETAILS_FAILURE = 'TRANSACTION_DETAILS_FAILURE'